<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>SecretsService.DataAccess</RootNamespace>
        <UserSecretsId>19ed03dd-33d2-4ac6-9ede-1039627a994f</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.8">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.8"/>
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="5.0.0"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="5.0.0"/>
    </ItemGroup>

</Project>
